# .github/workflows/release.yml

name: Release Go Binaries

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, linux/arm64, windows/amd64, windows/arm64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Get Tag Name
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and release Go binaries
      uses: wangyoucao577/go-release-action@v1
      with:
        asset_name: "protoc-gen-openapi-${{ env.TAG_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}"
        compress_assets: OFF
        sha256sum: TRUE
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
